### ISSUE TITLE
絵文字への対応

### ISSUE THREAD

**Issue by imamurayusuke** [rnanba/HatenaBlogWriter#11]
絵文字を扱えるようにはできますか?
多くの絵文字（🎉など）を記事に入れると「invalid byte sequence in UTF-8 (ArgumentError)」が出ます。
❤は大丈夫でした。
可能ならご検討ください。

**Comment by rnanba** [comment]
試してみましたがこちらでは再現しませんでした。

> ![image](https://github.com/rnanba/HatenaBlogWriter/assets/589746/726271ec-e3a5-4875-af41-f7fa432f5a56)

タイトル、カテゴリ、本文で🎉が使えています。

環境は以下の通りです。

- Ubuntu 20.04 
- ruby 2.7.0p0 
- atomutil 0.1.5

そちらの環境で気になる点があれば教えて下さい。あと、エントリファイルを何らかのツールで前処理してたりしませんか？

**Comment by imamurayusuke** [comment]
なんと、そうですか。確かにはてなブログライターの前にはてなブログライタースプリッタを使っています。そっちですかね。
https://github.com/imamurayusuke/HatenaBlogWriterSplitter
「はてダラスプリッタ」をちょっと書き替えて、はてなブログライター向けにしたものです。
なので内部動作はよくわかっておらず、こちらが原因ならあきらめる感じです。

**Comment by imamurayusuke** [comment]
すみません、わかりました。テキストエディタの問題でした。
hbw.rb newで作成したテキストファイルにWZ Editor 5.02Dで絵文字を記入して保存しhbw.rbしたところ最初のと同じエラーが出ました。
一方同じテキストファイルをVScodeで編集してから保存しhbw.rbした場合は問題なく投稿されました。
これであきらめがつきました。お騒がせしました。

それから、はてなブログライタースプリッタは今回の問題に関係ないことを確認しました。
全エントリをまとめたテキストファイルにVScodeで絵文字を記入してからはてなブログライタースプリッタ→hbw.rbと実行し、問題なく投稿されました。

**Comment by rnanba** [comment]
そういうことでしたか。WZ Editor のバグということなのか、それとも UTF-8 の仕様の範囲内だけど Ruby または hbw がエラーにしてしまうのか気になりますので時間があるときで構いませんので WZ Editor で保存したエラーになるファイルを添付していただけないでしょうか。

**Comment by imamurayusuke** [comment]
絵文字を含み、WZ Editor 5.02Dで保存したテキストファイルはこちらです。

- [2023-12-15_06.txt](https://github.com/rnanba/HatenaBlogWriter/files/13685095/2023-12-15_06.txt)

WZ Editor 5はたいへん古いエディタでして、バージョン情報によると5.02Dは2004年リリースのようです。
最新バージョンはよく使う機能が削除されたため、バージョンアップせずずっと使い続けているしろものです。
バージョン5は内部はShiftJISで処理されているとも聞きました。
そんななのでUnicodeまわりは弱く、絵文字にちゃんと対応していなくてもやむを得ないと考えています。

参考になれば幸いです。

**Comment by rnanba** [comment]
サンプル確認しました。UTF-8のテキストなのに何故か絵文字だけUTF-16で入ってますね… 
`0xF0 0x9F 0x8E 0x89` になるべきところが `0xD83C 0xDF89` になっています。
明らかに規格違反なので WZ Editor のバグですね。
回避方法としては入力時にHTMLの数値文字参照(`&#x1F389;` のような)で入力するくらいでしょうか。

**Comment by rnanba** [comment]
あ、すみません、勘違い。UTF-16 で入っているのではなくて、UTF-16 の `0xD83C 0xDF89` を `0xD83C` と `0xDF89` の2文字に分けて、それぞれを UTF-8 に変換して保存している、でした。要はサロゲートペアを一つの文字として正しく扱えていないのでバグというかサロゲートペア未対応(絵文字未対応)ということになります。

**Comment by imamurayusuke** [comment]
確認いただいてありがとうございます。確かにWZ5上でクラッカーは1文字として扱われておらず、左半分しか表示されませんし削除するときはDELやBSを2回押しています。
![emoji_on_WZ5](https://github.com/rnanba/HatenaBlogWriter/assets/8149723/17a42d68-0b0f-4137-b068-9cada7b8780a)

これまでの対応はおっしゃる通り、文字参照を調べて置き換えるという方法をとっています。
絵文字対応はテキストエディタを替えない限りどうにもならないとわかってすっきりしました。お手数をおかけしました。
