### ISSUE TITLE
最初の投稿の前にhbwdl.rbなどを実行するとdataフォルダがないためエラーになる

### ISSUE THREAD

**Issue by imamurayusuke** [rnanba/HatenaBlogWriter#9]
エントリを最初に投稿する前にhbwdl.rbを実行すると``data``フォルダがないというエラーが出ます。
```
Traceback (most recent call last):
        3: from C:/temp/new/hbw.rb:139:in `<main>'
        2: from C:/temp/new/hbw.rb:32:in `modified_files_to_update'
        1: from C:/temp/new/hbw.rb:32:in `foreach'
C:/hbw.rb:32:in `open': No such file or directory @ dir_initialize - data (Errno::ENOENT)
```
``hbw.rb check``などでも同様でした。
hbwdl.rbができたため、最初の投稿の前にまずhbwdl.rbを実行するケースがありそうです。できればご対応をお願いします。

**Comment by rnanba** [comment]
v0.9.1 で修正しました。なお、v0.9 の hbwdl (v0.1) でこのバグでダウンロードに失敗した場合、1件ダウンロードされたエントリがdataファイルのない状態で残ってしまいます。これをそのままにすると hbw で新規エントリファイルと誤認されて新規エントリとして投稿されてしまうので、削除してから再ダウンロードしてください。
